# fly.toml app configuration file generated for full-stack-open-relational-databases-2023 on 2023-11-23T21:47:24+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "full-stack-open-relational-databases-2023"
primary_region = "sin"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
