DELETE http://localhost:3001/api/logout
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImlsdmVzQGlraS5maSIsImlkIjozLCJpYXQiOjE3MDE1MTI4NTJ9.yil-FBMu-5_HDxRjKRmhRan-Md0s9XtviUY0UL2tap0